"""
Agent 2: Creative Idea Generator
Brainstorms creative gift concepts using Gemini Flash API
"""

import os
import json
import google.generativeai as genai
from typing import Dict, Any, List
from pydantic import BaseModel, Field

from agents.profile_analyzer import UserProfile

class GiftConcept(BaseModel):
    """Creative gift concept generated by Agent 2"""
    concept: str = Field(description="Creative gift concept description (20-50 words)")
    category: str = Field(description="Gift category (e.g., Electronics, Books, Fashion)")
    reasoning: str = Field(description="Why this concept matches recipient (15-30 words)")

class CreativeIdeaAgent:
    """Generates creative gift concepts based on user profile"""
    
    def __init__(self):
        # Initialize Gemini API
        api_key = os.getenv("GEMINI_API_KEY")
        if not api_key:
            raise ValueError("GEMINI_API_KEY environment variable not set")
        
        genai.configure(api_key=api_key)
        self.model = genai.GenerativeModel('gemini-1.5-flash')
        
        self.prompt_template = """
[System]
You are GiftPedia's Creative Idea Generator. Your task is to brainstorm creative gift concepts based on user profile.

Generate 3-5 creative gift concepts that would be perfect for the recipient. For each concept:
- Think beyond obvious gifts
- Consider recipient's interests and personality
- Match the occasion and relationship
- Respect budget constraints if mentioned
- Focus on unique, thoughtful ideas

Output ONLY a valid JSON array with objects:
[
  {
    "concept": "Creative gift concept description (20-50 words)",
    "category": "Gift category (e.g., Electronics, Books, Fashion, Home, Experience)",
    "reasoning": "Why this concept matches recipient (15-30 words)"
  }
]

[User Profile]
{profile_json}

Rules:
- Be creative and original
- Consider practicality and usefulness
- Match recipient's personality and interests
- If budget is specified, suggest concepts within range
- Output ONLY JSON array, no explanations
"""

    def generate_concepts(self, profile: UserProfile) -> List[GiftConcept]:
        """
        Generate creative gift concepts based on user profile
        
        Args:
            profile: Structured user profile
            
        Returns:
            List of creative gift concepts
        """
        try:
            # Generate prompt
            profile_json = profile.dict()
            prompt = self.prompt_template.format(profile_json=json.dumps(profile_json, indent=2))
            
            # Call Gemini API
            response = self.model.generate_content(prompt)
            
            # Extract JSON from response
            response_text = response.text.strip()
            
            # Clean response to extract JSON
            if "```json" in response_text:
                json_start = response_text.find("```json") + 7
                json_end = response_text.find("```", json_start)
                json_text = response_text[json_start:json_end].strip()
            else:
                json_text = response_text
            
            # Parse JSON
            concepts_data = json.loads(json_text)
            
            # Validate with Pydantic
            concepts = [GiftConcept(**concept) for concept in concepts_data]
            
            return concepts
            
        except json.JSONDecodeError as e:
            print(f"JSON parsing error: {e}")
            print(f"Raw response: {response_text}")
            # Return default concepts on error
            return [GiftConcept(
                concept="Personalized gift based on interests",
                category="Custom",
                reasoning="Tailored to recipient's preferences"
            )]
            
        except Exception as e:
            print(f"Creative idea generation error: {e}")
            # Return default concepts on error
            return [GiftConcept(
                concept="Personalized gift based on interests",
                category="Custom", 
                reasoning="Tailored to recipient's preferences"
            )]

    def test_generation(self, test_profiles: List[UserProfile]) -> List[Dict[str, Any]]:
        """
        Test concept generation with sample profiles
        
        Args:
            test_profiles: List of user profiles
            
        Returns:
            List of generation results
        """
        results = []
        for profile in test_profiles:
            try:
                concepts = self.generate_concepts(profile)
                results.append({
                    "profile": profile.dict(),
                    "concepts": [concept.dict() for concept in concepts],
                    "success": True
                })
            except Exception as e:
                results.append({
                    "profile": profile.dict(),
                    "error": str(e),
                    "success": False
                })
        return results

# Singleton instance
creative_idea_agent = CreativeIdeaAgent()

if __name__ == "__main__":
    # Test the agent
    from agents.profile_analyzer.agent import profile_analyzer
    
    test_profiles = [
        UserProfile(
            recipient_age=28,
            recipient_gender="male",
            interests=["music", "guitar", "audio"],
            relationship="family",
            occasion="birthday",
            budget_inr=2000,
            constraints=[]
        ),
        UserProfile(
            recipient_age=35,
            recipient_gender="female", 
            interests=["cooking", "gardening", "healthy_living"],
            relationship="partner",
            occasion="anniversary",
            budget_inr=5000,
            constraints=[]
        )
    ]
    
    agent = CreativeIdeaAgent()
    results = agent.test_generation(test_profiles)
    
    print("Creative Idea Generator Test Results:")
    print("=" * 50)
    for result in results:
        print(f"Profile: {json.dumps(result['profile'], indent=2)}")
        if result['success']:
            print("Generated Concepts:")
            for i, concept in enumerate(result['concepts'], 1):
                print(f"  {i}. {concept['concept']}")
                print(f"     Category: {concept['category']}")
                print(f"     Reasoning: {concept['reasoning']}")
        else:
            print(f"Error: {result['error']}")
        print("-" * 50)
